-- AlterTable
ALTER TABLE `category` MODIFY `updateAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `user` MODIFY `updateAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);
